version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Password.1'
      MSSQL_PID: 'Developer'
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: web_server
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - php

volumes:
  mssql_data:
