# Start from an official PHP-FPM image
FROM php:8.2-fpm-bullseye

# Environment variable to accept EULA for MS packages
ENV ACCEPT_EULA=Y

RUN apt-get update && \
    apt-get install -y \
        gnupg \
        unixodbc-dev \
        apt-transport-https \
        ca-certificates \
        curl \
        --no-install-recommends && \
    # Import and register Microsoft key and repository
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    # Install the MS ODBC Driver 17 for SQL Server
    apt-get install -y msodbcsql17 && \
    # Install and enable the PHP extensions from PECL
    pecl install sqlsrv pdo_sqlsrv && \
    docker-php-ext-enable sqlsrv pdo_sqlsrv && \
    # Clean up
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
